version: '3.8'

services:
  esb:
    container_name: esb
    image: hellohasty/esb-image:latest
    build:
      context: .
      dockerfile: Dockerfile.esb
    ports:
      - "3000:3000"
    env_file:
      - configs/config.env

  auth-service:
    container_name: auth-service
    image: hellohasty/auth-service-image:latest
    build:
      context: .
      dockerfile: Dockerfile.auth-service
    ports:
      - "3001:3001"
    env_file:
      - configs/config.env

  user-service:
    container_name: user-service
    image: hellohasty/user-service-image:latest
    build:
      context: .
      dockerfile: Dockerfile.user-service
    ports:
      - "3002:3002"
    env_file:
      - configs/config.env

  transaction-service:
    container_name: transaction-service
    image: hellohasty/transaction-service-image:latest
    build:
      context: .
      dockerfile: Dockerfile.transaction-service
    ports:
      - "3003:3003"
    env_file:
      - configs/config.env

  topup-service:
    container_name: topup-service
    image: hellohasty/topup-service-image:latest
    build:
      context: .
      dockerfile: Dockerfile.topup-service
    ports:
      - "3004:3004"
    env_file:
      - configs/config.env

networks:
  default:
    driver: bridge