FROM node:22-alpine3.19

WORKDIR /opt/program

RUN ls

COPY configs /opt/program/configs
COPY common /opt/program/common
COPY db /opt/program/db
COPY services/user-service /opt/program/services/user-service

WORKDIR /opt/program/services/user-service

RUN npm install

ENTRYPOINT [ "npm", "start" ]